name: Deploy to Tenderly
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Get that code
        uses: actions/checkout@v3
      - name: Deploy
        run: |
          curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sh
          tenderly login --authentication-method access-key --access-key ${{ secrets.TENDERLY_ACCESS_KEY }} --email ${{ secrets.TENDERLY_EMAIL }}
          tenderly actions deploy
